### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: 'certs/icao_pkd_ml' (issue by @gbmamat)

### ISSUE THREAD

**Issue by Fethbita** [Fethbita/eMRTD_face_access#6]
Original from https://github.com/Fethbita/eMRTD_face_access/commit/e0167b107fed93d710f79ef11a6b4e0d36ff9bdc#commitcomment-66542414.

----

dear,
I try  to  process in  backend side   with  backend   Flask endpoint   https:///samples.com/v1/api/passiveAuth.  These  endpoint  will   upload  SODFile  as base64  to  backend server.

some things like this

```python
from passive_authentication import (
    passive_auth,
    PassiveAuthenticationCriticalError,
)
from valid import download_certs
from icao_pkd_load import build_store
import os
from pathlib import Path
import base64


data ="""
d4IIzTCCCMkGCSqGSIb3DQEHAqCCCLowggi2AgEDMQ8wDQYJYIZIAWUDBAIDBQAwggGNBgZngQgB
AQGgggGBBIIBfTCCAXkCAQAwDQYJYIZIAWUDBAIDBQAwggFjMEUCAQEEQKd6LOBCwGcqeh/KYclP
j0nBuyFAaBMwk911RY6/xlXDDfqSvpUKekuecGlGpemeMnd2dIXoA14MWVBaRpcHZDkwRQIBAgRA
DonlwyPs5elPxB84jzBdKn0qnKVX6JfHsZoaOTZrTrASThTaRSIFVHAvSCJVTDgMYGrf0kBR4PRI
1hyfBFgNRzBFAgEHBEC4sUnCvDNAnGbaUP+6R5FMCa9taqR39HL4ZCs86NTtMg493OqFe+dta3MD
2XNLO+kdp5IBFm2BzTkmT2WsF0CTMEUCAQ4EQLMO7QiouSC0IXvv186U6wdSEbJ454y333e/skH1
8GlhM72R5ONh+6vuFC8zbH8Bm+TLQOistkIS22S3rMSHrh0wRQIBDwRAFFChsZtgEYXXrGpctmpR
rOv/uDSz9kaSf1pcIfGZW5gOwBsYZx82+ETGYjL6zPCNBFLgRiMz2TCS5NS80mdfbKCCBM4wggTK
MIICsqADAgECAgRXMu9QMA0GCSqGSIb3DQEBDAUAMEYxEjAQBgNVBAMMCUNTQ0FfRFBSSzEMMAoG
A1UECgwDTUZBMRUwEwYDVQQLDAxQYXNzcG9ydFVuaXQxCzAJBgNVBAYTAktQMB4XDTE2MDUxMTAw
MDAwMFoXDTI3MDcxMTAwMDAwMFowRDEQMA4GA1UEAwwHRFNfRFBSSzEMMAoGA1UECgwDTUZBMRUw
EwYDVQQLDAxQYXNzcG9ydFVuaXQxCzAJBgNVBAYTAktQMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEAlrugYORjWDLXT+0C6YShJSN7kNq7Ifu5ZPXrwB0nlwLwdCPo/pfR0y3AMNBmzxoI
1g+4cc5Nwm3pKmSIgzgGdbc8Et0e8Hg6qSaNbRW53I+L1Uy/2ev1LSlz4tGdWL7ozHgo4p41UklP
VCTpAGvAlpncbWPjGmVmUHD4cuCfgt73kk+6EM0hMuucZXq+olT/2d9xRUfIbv4e1JYh+FZ54DsJ
RtaC6hsEhhXlfzpnJnEQLXxypS5Tdi9YUe0aZYpYzGYfnBMSoJ/1lCUaU5pMRM0EW2hWEnqyygf1
zy3Jx0F1dZ5RV7duTGNzRn+UnqKQcL/ssLFQ4yo/L/5OWRd2tQIDAQABo4HBMIG+MHEGA1UdIwRq
MGiAFNR9cbKREr4EQceQAL9PUbtDMPXKoUqkSDBGMRIwEAYDVQQDDAlDU0NBX0RQUksxDDAKBgNV
BAoMA01GQTEVMBMGA1UECwwMUGFzc3BvcnRVbml0MQswCQYDVQQGEwJLUIIEVzLqUzAOBgNVHQ8B
Af8EBAMCB4AwDAYDVR0TAQH/BAIwADArBgNVHRAEJDAigA8yMDE2MDUxMTAwMDAwMFqBDzIwMTcw
NjExMDAwMDAwWjANBgkqhkiG9w0BAQwFAAOCAgEAVYVXpUANQNFXt7GLR1sRtcl3w3CeNZpiDZ7N
dbDvLT9UbLJmF1rrf79VaaS8+Ox4QxtM+7pQXti8arJqMJ9oLOb1qbWinF31XjHLJtc1FRtw2nQY
tvbyQJlorA7FZhm2vj/gIETgg2ux+0HDaiRDavs3b3yiq3VTRR+cuIa3HY3aoCDdBe4ULMTbf62w
ZrQJAmWBkIB9RmUsPoL9tDgb9O40LgWwQ+oPa24bMw3S4qosI8q/+YrSN9frpwzDbCTfLOfOB6/C
tpmuo+BTFllgL0UjpcidO3q7x400bLnZJaHnRJFuc8Iov5ihVKsaYLIOI+vpttUnPBUKCYhBMdAo
IPigrBHGrKMnafXTZklOrUpphsFWiQ01T3LHu56XCTpvvUTO4/UIw7ey8hgYW01t2o69q1YpJnG3
rfn/PnrdYu5rhEPlj7DxeyRz4L+EyluPR/cm9a9/SZe3GWS0+WKlgDG9Tqe7C1a8QyJP0/4w885B
8I8wKp1Tn3lOqxbzrHqQhCmKqCELkGC7Jq8eultek+DjniMLy1GWWRTG3C8IT852++Sy9bfMDha0
M2nzmb+0WH/LAF8O5S5dPSNdtQXOurTQdkHBxFpgFBEIjgjdSI/mDKN1JPKQkvMDIUd4gX2N/pyG
7cViod+A9eVzlIhbipHMN9gHnXzCmaC+LZbNYKoxggI7MIICNwIBATBOMEYxEjAQBgNVBAMMCUNT
Q0FfRFBSSzEMMAoGA1UECgwDTUZBMRUwEwYDVQQLDAxQYXNzcG9ydFVuaXQxCzAJBgNVBAYTAktQ
AgRXMu9QMA0GCWCGSAFlAwQCAwUAoIGGMBUGCSqGSIb3DQEJAzEIBgZngQgBAQEwHAYJKoZIhvcN
AQkFMQ8XDTE2MTEyMjA4MzQxNVowTwYJKoZIhvcNAQkEMUIEQBi1YT+yTDlWiKgORwwA1ZcGX9/B
bDzJGfqfoS3lfTxpcIGd7ntxWroPK5zCJJf8JLKLkYdMWroTzotLgBdInD4wRgYJKoZIhvcNAQEK
MDmgDzANBglghkgBZQMEAgMFAKEcMBoGCSqGSIb3DQEBCDANBglghkgBZQMEAgMFAKIDAgFAowMC
AQEEggEAfj8R7ucrZ/bLkRKDj4car+covU3tQed9hegCJ3o0bF1W2Zw2YynsQDv3c0sLkl8k7IL4
BRRs1gQdBj5dKAH3psSwRgwNtuu+7uswxntGA0+fymSkVavUGIN15/7XCkNlTRkpU/tHyutGOZd3
XFopTL57MFx1plkpBunThEI8ng3hmXCXVrpf0uWaeLLfzgzGA8qzNZIuIWsZcdxbL5203tHYNfgf
vem9/RzeMlUPr7t8Ujdbv5Ka+IfW4yZ53uziUiUqWq9ilWopC00ZjvMiycwXOdM2iZu/1vR8mySF
bBYYGiyVy3C9+51hSru0bSsxAvbMmK1NkA7hHLOmFCQnng==
"""
sod = base64.b64decode(sodData)

 CSCA_certs_dir = Path("certs/")

 crls_dir = Path("certs/crls")

 download_certs(CSCA_certs_dir, crls_dir)

 dsccrl_dir = Path(os.path.join(os.path.dirname(CSCA_certs_dir), Path("icao_pkd_dsccrl")))

 ml_dir = Path(os.path.join(os.path.dirname(CSCA_certs_dir), Path("icao_pkd_ml")))

 build_store(CSCA_certs_dir, crls_dir, ml_dir, dsccrl_dir)


 try:
        passive_auth_return = passive_auth(sod, deviant_doc=False, dump=False)
        result =  {
                     "status": "200",
                     "message":" Successfull done!",
                     "result": passive_auth_return,
                     "authenticity": "SUCCESSED"

                  }
        return result
    except PassiveAuthenticationCriticalError as ex:
         result =  {
                     "status": "400",
                     "message":"Passive Authentication Critical Error!",
                     "authenticity": "FAILED"

                  }
        return result
```

But, I got  following  error 

 build_store(CSCA_certs_dir, crls_dir, ml_dir, dsccrl_dir)
  File "/home/devadmin/com.biomiid.kyx/backend/icao_pkd_load.py", line 41, in build_store
    with open(os.path.join(CSCA_certs_dir, file), "rb") as infile:
IsADirectoryError: [Errno 21] Is a directory: 'certs/icao_pkd_ml'

Please, can  you  help me to fix this  issue?

Thank you  in advance.

Regards,

**Comment by Fethbita** [comment]
The arguments for build_store should each be folders that contain the items directly as files. So in this case, you should have a `CSCA_certs_dir` that has certificates that you want to add as an extra (that are not in any ML for example), `crls_dir` should contain CRLs and so on. Do not create a `CSCA_certs_dir` to contain all the other folders (`crls_dir`, `ml_dir`, `dsccrl_dir`).
You can see how this is achieved in [main_program_loop.py](https://github.com/Fethbita/eMRTD_face_access/blob/0f9cf2dd04559710720cac3a1109118c4bea6ed8/emrtd_face_access/main_program_loop.py#L107):

```python
# ...
CSCA_certs_dir = args.certs or Path("certs/csca_certs")
crls_dir = args.certs or Path("certs/crls")
# ...
# note that os.path.dirname gets the directory name, not the name of the folder itself (in this case just certs)
dsccrl_dir = Path(os.path.join(os.path.dirname(CSCA_certs_dir), Path("icao_pkd_dsccrl")))
ml_dir = Path(os.path.join(os.path.dirname(CSCA_certs_dir), Path("icao_pkd_ml")))
# ...
build_store(CSCA_certs_dir, crls_dir, ml_dir, dsccrl_dir)
```

**Comment by gbmamat** [comment]
Thank you for your reply.

in  my use case I want  support ICAO PKD   countries members(not  only individual country  like  on your demo use case EE)   used   ML, DSCRL,  NC    .ldip  files, so  will support all  ICAO PKD members countries (82 countries)


Regards

**Comment by Fethbita** [comment]
You can leave the `CSCA_certs_dir` directory empty if you do not want to add an individual country. If you are already adding and using MLs, then they should be used. Let me know if this helped you solve your issue.

**Comment by gbmamat** [comment]
ml_dir, dsccrl_dir   directories  depended of  CSCA_certs_dir

**Comment by gbmamat** [comment]
I'm  created  tree different directories : 

dsccrl_dir = Path("certs/icao_pkd_dsccrl")
ml_dir = Path("certs/icao_pkd_ml")
nc_dir = Path("certs/icao_pkd_nc")

# ...
build_store(ml_dir, dsccrl_dir, nc_dir)

**Comment by gbmamat** [comment]
Now  i got  passive auth   verification result

[+] CertificateSet exist
[+] Document Signer Certificate is signed by a CSCA certificate
[+] Content Type of eContent match with the Content Type in SignedAttributes
[+] Hash of eContent match with the hash in SignedAttributes
[+] The signature on EF_SOD is valid.

**Comment by gbmamat** [comment]
how to  integrate   nc_dir  icaopkd-003-nc-xxxxxx.ldif     in  pypassport?

**Comment by Fethbita** [comment]
> how to integrate nc_dir icaopkd-003-nc-xxxxxx.ldif in pypassport?

Unfortunately NC document handling is not supported.

It is only implemented for Estonian ID card cases, where the C<sub>DS</sub>s included in the eMRTD chips, in their `notBefore` and `notAfter` fields had a 12-hour negative offset compared to the original C<sub>DS</sub> that was signed. The workaround for this single case can be seen in https://github.com/Fethbita/eMRTD_face_access/blob/0f9cf2dd04559710720cac3a1109118c4bea6ed8/emrtd_face_access/main_program_loop.py#L291-L300 and https://github.com/Fethbita/eMRTD_face_access/blob/0f9cf2dd04559710720cac3a1109118c4bea6ed8/emrtd_face_access/passive_authentication.py#L116-L129

**Comment by gbmamat** [comment]
Thank you  so much  for  your reply  and time.

Have good day


see you   later

**Comment by Fethbita** [comment]
Thank you for showing interest on this project and creating an implementation using it. Have a nice day
